home/urls.py
from django.urls import path
from home import views

app_name='home'
urlpatterns = [
    # http://127.0.0.1:8000/
    path('', views.index, name='index'),
    path('countries/', views.countries),  # http://127.0.0.1:8000/countries/
    path('about/', views.about),  # http://127.0.0.1:8000/about/
    path('about/<int:year>', views.about),  # http://127.0.0.1:8000/about/2000
    path('categories/', views.categories), # http://127.0.0.1:8000/categories/
    path('cities/', views.cities),    # http://127.0.0.1:8000/cities/
]

member/urls.py
from django.urls import path
from member import views 

app_name='member'
# http://127.0.0.1:8000/member/
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='create'), # http://127.0.0.1:8000/member/register/
    
    path('edit/', views.edit, name='edit'), # http://127.0.0.1:8000/member/edit/
    path('delete/<int:id>', views.delete, name='delete'),
    path('mobile/', views.mobile, name='mobile'), # http://127.0.0.1:8000/member/mobile/
    path('formdemo/', views.formdemo, name='form'),
    path('write/', views.write, name='write'),
    path('read/', views.read, name='read'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# from member import views as member_view
# from home import views as home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # http://127.0.0.1:8000/
    path('',include('home.urls')),  # 載入 home 下面的 urls.py
     # http://127.0.0.1:8000/member/
    path('member/',include('member.urls')),
    # http://127.0.0.1:8000/store/
    path('store/', include('myapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

member/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Member(models.Model):
    member_id = models.AutoField(primary_key=True)
    member_name = models.CharField(max_length=20, unique=True)
    member_password = models.CharField(max_length=128)
    member_birth = models.DateField()
    member_email = models.EmailField(max_length=200, unique=True, default='')
    member_avatar = models.CharField(max_length=100, default='empty.png')
    last_update = models.DateTimeField(default=datetime.now())

    class Meta:
        db_table = 'member'  # 指定的資料表名稱
        
       

member/forms.py
from django import forms
from .models import Member

# Form API
class MemberForm(forms.Form):
    member_name =  forms.CharField(label='姓名', max_length=100)
    member_email = forms.CharField(label='電子郵件', max_length=200)

# Forms By Model
class UserForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['member_name','member_birth','member_email']

member/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect 
from django.core.files.storage import FileSystemStorage
from .models import Member
from django.contrib.auth.hashers import make_password, check_password
from .forms import MemberForm, UserForm
from datetime import datetime, timedelta

# Create your views here.
def index(request):
    
    # print(request.headers)

    # 讀出 headers 裡面的某類型的資料
    # print(request.headers.get('Content-Type'))
    # print(request.headers.get('User-Agent'))

    # 讀出 headers 中所有的資料
    # html += '<ul>'
    # for key, value in request.headers.items():
    #     html += f'<li>{key}：{value}</li>'
    # html += '</ul>'

    # user_agent = request.headers.get('User-Agent')
    # print('Mobile' in user_agent)
    # if 'Mobile' in user_agent:
    #     return redirect('/member/mobile/')

    # http method：GET、POST、PUT、DELETE...
    # print(request.method)  # GET

    # 讀取透過GET傳過來的資料 ?key=value
    # name = request.GET.get('username') # 讀不到 username 回傳 None
    # if name is None:
    #     name = 'Django'    
    # html = f'<h2>Hello {name}</h2>'

    # response = HttpResponse(html)
    # response.status_code = 200
    # [{},{}]
    # response['Content-Type'] = 'application/json'
    # response.encoding = 'utf-8'


    # return HttpResponse(html)
    # return render(request,'member/index.html',{})


    # 資料庫操作 CRUD
    # 新增
    # Member.objects.create(
    #     member_name = 'Jack',
    #     member_password = '12345678',
    #     member_birth = '1998-11-20',
    #     member_email = 'Jack@gmail.com'
    # )

    # # 讀取所有會員資料
    # members = Member.objects.all()
    # print(members)

    # # 讀取單筆資料
    # member = Member.objects.get(member_id=2)    
    # print(member)

    # 修改
    # 先找到要修改的資料
    # member = Member.objects.get(member_id=2)  
    # # 進行修改
    # member.member_name = 'Jack2'
    # member.member_birth = '1998-01-20'
    # # 將修改完的結果更新到資料庫
    # member.save()

    # 刪除
    #  # 先找到要刪除的資料
    # member = Member.objects.get(member_id=2)  
    # # 進行刪除
    # member.delete()



    # return HttpResponse('資料庫操作練習')

    # 讀取會員所有資料
    members = Member.objects.all()
    return render(request, 'member/index.html',{'members': members})

def register(request):
    if request.method == 'POST':
       
        # 接收使用者上傳的資料
        name = request.POST.get('username')
        email = request.POST.get('useremail')
        password = request.POST.get('userpassword')
        birth = request.POST.get('userbirth')

         # 接收上傳的檔案
        avatar = request.FILES.get('userphote')
        # # 檔案名稱
        file_name = avatar.name
        # # 檔案大小
        # file_size = avatar.size
        # # 檔案類型
        # file_type = avatar.content_type

        # print(f'檔案名稱：{ file_name }')
        # print(f'檔案大小：{ file_size }')
        # print(f'檔案類型{ file_type }')

        # 將上傳檔案儲存到uploads資料夾
        fs = FileSystemStorage()
        upload_file = fs.save(file_name, avatar)

        
        Member.objects.create(
            member_name = name,
            member_password = make_password(password), 
            member_birth = birth,
            member_email = email,
            member_avatar = upload_file
        )

        return redirect('member:index')


       
        # print(f'upload file:{ upload_file }')
        
    return render(request, 'member/register.html',)

# /edit/?id=5
def edit(request):
    if request.method == 'POST':
        # 接收使用者上傳的資料
        id = request.POST.get('userid')
        name = request.POST.get('username')
        email = request.POST.get('useremail')    
        birth = request.POST.get('userbirth')
         # 接收上傳的檔案
        avatar = request.FILES.get('userphote')
        file_name = avatar.name
        # 將上傳檔案儲存到uploads資料夾
        fs = FileSystemStorage()
        upload_file = fs.save(file_name, avatar)
        # 修改到資料庫
        member = Member.objects.get(member_id=id) 
        member.member_name = name
        member.member_email = email
        member.member_birth = birth
        member.member_avatar = upload_file
        member.save()
        return redirect('member:index')

  

    id  = request.GET.get('id', 1)
    member = Member.objects.get(member_id=id)  
    return render(request, 'member/edit.html',{'member': member})


# /delete/1
def delete(request, id):   
    member = Member.objects.get(member_id=id)  
    member.delete()

    return redirect('member:index')


def mobile(request):
    return HttpResponse('<h2>Mobile 專屬</h2>')

def formdemo(request):
    form = MemberForm()
    userForm = UserForm()
    return render(request, 'member/formdemo.html', locals())

def write(request):
    response = render(request, 'member/write.html', locals())
    title = "cookie demo"
    # 已經登入

    # 將資料寫進cookies
    response.set_cookie('is_login', True)
    # 將資料寫進session
    request.session['name'] = 'Jack'

    # return render(request, 'member/write.html',{'title': title})
    return response


def read(request):
    title = "abcdefg"

    # 讀取 cookie
    is_login = request.COOKIES.get('is_login')    
    print(is_login)

    # 讀取 session
    if 'name' in request.session:
        name = request.session['name']
    else:
        name = 'guest'
    print(name)

    return render(request, 'member/read.html',{'title': title})

def login(request):
    if request.method == 'POST':
        # 接收表單傳過來的資料
        member_name = request.POST.get('member_name')
        member_password = request.POST.get('member_password')
        remember_me = request.POST.get('remember_me')

        # print(member_name)
        # print(member_password)
        # print(remember_me)
        
        message = ''

        # 檢查是否有此帳號
        member = Member.objects.filter(member_name=member_name).first()
        if member:            
            message = '有此帳號'
            # 檢查密碼是否正確
            if check_password(member_password, member.member_password):
                response = HttpResponse('<script>alert("登入成功");location.href="/member/"</script>')
                message = '有此帳號且密碼正確'
                # 表示登入成功，我們要將登入成功的資訊存進cookie或者是session
                if remember_me == 'on':
                    # 保留 cookie 的值一段時間
                    maxAgeTime = timedelta(minutes=1)
                    response.set_cookie('name', member_name, max_age=maxAgeTime)
                    
                else:
                    # 瀏覽器關掉就讓 cookie 的值消失
                    response.set_cookie('name', member_name)
                    
                # 轉到會員首頁
                return response
            else:
                message = '密碼不正確'

        else:
            message = '查無此帳號'

        return render(request, 'member/login.html', {'message': message})


    return render(request, 'member/login.html')

def logout(request):
    # 清除 session 中的資料
    request.session.clear()

    # 清除 cookie 中的資料
    response = HttpResponse('<script>alert("登出成功");location.href="/member/login"</script>')
    response.delete_cookie('name')
    response.delete_cookie('is_login')

    return response

member/templates/member/edit.html
{% extends 'base.html' %}
{% block title %}
<h3>會員修改</h3>
{% endblock %}

{% block content %}
<!--
    檔案上傳表單的必要設定
    1. form 標籤 enctype="multipart/form-data"
    2. <input type="file" name="userimage" />
    -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <input type="hidden" name="userid" value="{{ member.member_id }}" />
            <input type="text" name="username" placeholder="請輸入姓名" value="{{ member.member_name }}">
        </div>
        <div>
            <input type="email" name="useremail" placeholder="請輸入電子郵件" value="{{ member.member_email }}">
        </div>
        <div>
            <input type="date" name="userbirth" value="{{ member.member_birth|date:'Y-m-d' }}">
        </div>
        <div>
            <input style="display: none;" type="file" name="userphote" id="file1"/>
            <div>
                <small>click image 進行修改</small><br />
               <img id="img1" src="{{MEDIA_URL}}{{member.member_avatar}}" alt="{{member.member_name}}" /> 
            </div>
            
        </div>
        <button type="submit">修改</button>
    </form>
{% endblock %}

{% block scripts %}
  <script>
    const theFile = document.querySelector('#file1')
    const theImg  = document.querySelector('#img1')
    theImg.addEventListener('click',()=>{
        theFile.click()
    })
    theFile.addEventListener('change',()=>{
       //顯示圖 FileReader API
       const reader = new FileReader();
       reader.readAsDataURL(theFile.files[0]); //讀圖
       //完成後會觸發load事件
       reader.addEventListener('load',()=>{
        theImg.src = reader.result
       })
    })
  </script>
{% endblock %}

member/templates/member/formdemo.html
{% extends 'base.html' %}

{% block content %}
<form>
     {{ form }}
     <hr />
     {{ userForm }}
     <button type="submit">送出</button>
</form>
 
{% endblock %}

member/templates/member/index.html
{% extends 'base.html' %}
{% block styles %}
{% endblock %}

{% block title %}
<h3>會員管理</h3>
{% endblock %}

{% block content %}
<a href="{% url 'member:create' %}" class="btn btn-primary">新增</a>
<p>MediaURL：{{ MEDIA_URL }}</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>會員編號</th>
            <th>會員名稱</th>
            <th>電子郵件</th>
            <th>會員生日</th>
            <th>圖像</th>
            <th>編輯</th>
        </tr>
    </thead>
    <tbody>
        {% for member in members %}
        <tr>
            <td>{{ member.member_id }}</td>
            <td>{{ member.member_name }}</td>
            <td>{{ member.member_email }}</td>
            <td>{{ member.member_birth }}</td>
            <td><img style="width:80px" alt="{{ member.member_name }}" src="{{MEDIA_URL}}{{ member.member_avatar }}" /></td>
            <td>
                <a href="{% url 'member:edit' %}?id={{member.member_id}}" class="btn btn-primary">修改</a>
                <a href="{% url 'member:delete' member.member_id %}" class="btn btn-danger" onclick="return confirm('真的要刪除嗎?')">刪除</a>
            </td>
        </tr>
        {% endfor %}
       
    </tbody>
</table>
{% endblock %}

{% block scripts %}
{% endblock %}

member/templates/member/login.html
<!doctype html>
<html lang="zh-tw">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登入</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body class="bg-dark bg-opacity-75">
    <div class="containe vh-100">
        <div class="row vh-100">
            <div class="col-4 m-auto p-5 justify-content-center bg-white rounded">
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label for="InputName" class="form-label">帳號</label>
                      <input type="text" name="member_name" class="form-control" id="InputName" >                     
                    </div>
                    <div class="mb-3">
                      <label for="InputPassword" class="form-label">密碼</label>
                      <input type="password" name="member_password" class="form-control" id="InputPassword">
                    </div>
                    <div class="mb-3 form-check">
                      <input type="checkbox" name="remember_me" class="form-check-input" id="RememberCheck">
                      <label class="form-check-label" for="RememberCheck">記住我</label>
                    </div>
                    <button type="submit" class="btn btn-primary">登入</button>
                  </form>
                  
                  <div class="alert alert-warning mt-3">
                    {{ message }}
                  </div>

            </div>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

member/templates/member/read.html
{% extends 'base.html' %}

{% block content %}
<h2>read something</h2> 
<p>{{ title }}</p>
{% endblock %}

member/templates/member/register.html
{% extends 'base.html' %}
{% block title %}
<h3>會員新增</h3>
{% endblock %}

{% block content %}
<!--
    檔案上傳表單的必要設定
    1. form 標籤 enctype="multipart/form-data"
    2. <input type="file" name="userimage" />
    -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="username" class="form-label">姓名</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="請輸入姓名">
        </div>
        <div class="mb-3">
            <label for="useremail" class="form-label">電子郵件</label>
            <input type="email"class="form-control" name="useremail"  id="useremail" placeholder="請輸入電子郵件">
        </div>
        <div class="mb-3">
            <label for="userpassword" class="form-label">密碼</label>
            <input type="password" class="form-control" name="userpassword" id="userpassword">
        </div>
        <div class="mb-3">
            <label for="userpassword1" class="form-label">密碼確認</label>
            <input type="password" class="form-control" name="userpassword1" id="userpassword1">
        </div>
        <div class="mb-3">
            <label for="userbirth" class="form-label">生日</label>
            <input type="date" class="form-control" name="userbirth"  id="userbirth">
        </div>        
        <div class="mb-3">
            <label for="userphote" class="form-label">頭像</label>
            <input type="file" class="form-control" name="userphote" id="userphote"/>
        </div>
        <button type="submit" class="btn btn-primary">註冊</button>
    </form>
{% endblock %}

member/templates/member/write.html
{% extends 'base.html' %}

{% block content %}
<h2>write something</h2> 
<p>{{ title }}</p>
{% endblock %}