home/urls.py
from django.urls import path
from home import views

app_name='home'
urlpatterns = [
    # http://127.0.0.1:8000/
    path('', views.index, name='index'),
    path('countries/', views.countries),  # http://127.0.0.1:8000/countries/
    path('about/', views.about),  # http://127.0.0.1:8000/about/
    path('about/<int:year>', views.about),  # http://127.0.0.1:8000/about/2000
    path('categories/', views.categories), # http://127.0.0.1:8000/categories/
    path('cities/', views.cities),    # http://127.0.0.1:8000/cities/
]

member/urls.py
from django.urls import path
from member import views 

app_name='member'
# http://127.0.0.1:8000/member/
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='create'), # http://127.0.0.1:8000/member/register/
    
    path('edit/', views.edit, name='edit'), # http://127.0.0.1:8000/member/edit/
    path('delete/<int:id>', views.delete, name='delete'),
    path('mobile/', views.mobile, name='mobile'), # http://127.0.0.1:8000/member/mobile/
    path('formdemo/', views.formdemo, name='form'),
    path('write/', views.write, name='write'),
    path('read/', views.read, name='read'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

myapp/urls.py
from django.urls import path
from myapp import views

app_name='myapp'
urlpatterns = [
    # path('比對的路徑','要執行的function')
    # http://127.0.0.1:8000/store/
    path('', views.index, name='index'),

    # http://127.0.0.1:8000/store/details/uuid
    path('details/<uuid:product_id>', views.details),
    # http://127.0.0.1:8000/store/about/
    path('about/', views.about, name='about'),
     # http://127.0.0.1:8000/store/about/2000
    path('about/<int:year>', views.about),
     # http://127.0.0.1:8000/store/blog/2024/7/1
    path('blog/<path:publish>', views.blog),
    path('course/<slug:course_name>', views.course),
     # http://127.0.0.1:8000/store/show  
    path('show/', views.show, name='show'),
    #  http://127.0.0.1:8000/store/abc/ 
    path('abc/', views.abc, name="contact")
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# from member import views as member_view
# from home import views as home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    # http://127.0.0.1:8000/
    path('',include('home.urls')),  # 載入 home 下面的 urls.py
     # http://127.0.0.1:8000/member/
    path('member/',include('member.urls')),
    # http://127.0.0.1:8000/store/
    path('store/', include('myapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->
     <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}" />
     {% block styles %}
     {% endblock %}
  </head>
  <body>
    <div class="container">
        <div class="pb-3">
          {% include 'navbar.html' %}
        </div>
          <div class="card">
            <div class="card-header">
                {% block title %}
                <p>My Title</p>
                {% endblock %}
            </div>
            <div class="card-body">
                {% block content %}
                <p>這裡的內容會被換掉</p>
                {% endblock %}
            </div>
          </div>
    
        {% include 'footer.html' %}
        </div>
   
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> -->
     <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
     {% block scripts %}
     {% endblock %}
  </body>
</html>

templates/footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2024 Company, Inc</p>
  </footer>

templates/index.html
<!DOCTYPE html>
<html lang="zh-hant-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>專案的 Index Page</h2>
</body>
</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/Logos.png' %}" alt="Bootstrap" width="50" height="24">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <!-- <a class="nav-link active" aria-current="page" href="/">Home</a> -->
            <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link active" aria-current="page" href="/store/">Store</a> -->
            <a class="nav-link active" aria-current="page" href="{% url 'myapp:index' %}">Store</a>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link" href="/store/about/">about</a> -->
            <a class="nav-link" href="{% url 'myapp:about' %}">about</a>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link" href="/store/show/">show</a> -->
            <a class="nav-link" href="{% url 'myapp:show' %}">show</a>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link" href="/store/abc/ ">abc</a> -->
            <a class="nav-link" href="{% url 'myapp:contact' %}">abc</a>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link" href="/store/abc/ ">abc</a> -->
            <a class="nav-link" href="{% url 'member:index' %}">會員管理</a>
          </li>
          
        </ul>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">     
            {% if 'name' in request.COOKIES %}    
            <a class="nav-link" href="{% url 'member:logout' %}">登入帳號:{{ request.COOKIES.name }} 登出</a>
            {% else %}            
            <a class="nav-link" href="{% url 'member:login' %}">登入</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>